## 설정들을 적어주는 환경파일
## resources/application.properties
#
#server.port=8081
#
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#
## custom 속성:  @Value 확인
#app.title=스프링 부트 애플리케이션
#
## 위 파일 삭제 후 resources/application.yml로 변경 후 확인
##spring:
##  application:
##    name: fisa
##  datasource:
##    url: jdbc:h2:mem:testdb
##    driver-class-name: org.h2.Driver
##    username: sa
##    password:
##  jpa:
##    database-platform: org.hibernate.dialect.H2Dialect
##  h2:
##    console:
##      enabled: true
##
##app:
##  title: 스프링 부트 애플리케이션
